### PR TITLE
add traefik as the default ingress

### PR DESCRIPTION
**Pull request by displague**
This introduces Traefik as the default ingress, running as a DaemonSet listening on Port 80/8080 of the nodes.
* https://docs.traefik.io/user-guide/kubernetes/

Is traefik the best choice? 
* https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/#additional-controllers

Should this listen on port 443 too?

Borrowing from kube-linode, other ideas to consider:
* https://github.com/kahkhang/kube-linode/blob/master/manifests/traefik.yaml#L58-L59
  this sets up a secret for the traefik control panel and configures an ingress for it

### CODE REVIEW

**Comment by displague** [comment]
This should be updated for Traefik 2.0 (even the current _alpha_, for the sake of reviewing the PR early)

* https://docs.traefik.io/v2.0/
* https://blog.containo.us/back-to-traefik-2-0-2f9aa17be305
* https://blog.codecentric.de/en/2019/04/traefik-2-0-configuration-routing-rule-syntax/

**Comment by jnschaeffer** [comment]
Taking a look at this thanks to @adammohammed bringing it to my attention.

Do we still want to use Traefik? Why not nginx?

**Comment by displague** [comment]
@jnschaeffer You can bounce this idea off @asauber.  We didn't have the strongest of opinions one way or the other on which Ingress to bundle by default.

All other Traefik vs Nginx concerns aside (https://caylent.com/kubernetes-top-ingress-controllers/  - best I could find :man_shrugging:), Linode is included as an ACME provider in Traefik: https://docs.traefik.io/configuration/acme/#provider 

In terms of providing a very Linode experience, it seemed like a good fit.

Nginx-Ingress also has some [built in TLS managing support, but it is deprecated](https://kubernetes.github.io/ingress-nginx/user-guide/tls/#automated-certificate-management-with-kube-lego), replaced by certmanager, which I believe also uses https://github.com/go-acme/lego/pull/622 - so this point may be awash.

I left the PR open hoping to take advantage of Traefik 2.0 to help seal the deal. 
https://blog.containo.us/back-to-traefik-2-0-2f9aa17be305#4b08

**Comment by displague** [comment]
That said - I believe there was nothing wrong with this PR as-is (consider adding 443 though).

**Comment by asauber** [comment]
Nginx as of a few months ago would drop all connections on configuration of an Ingress resource, whereas Envoy-based Contour would not in most cases. I don't know much about Traefik but this looks like a good start.

I'd like to see someone internal (maybe myself) test this out before merging.

**Comment by displague** [comment]
https://webworxshop.com/internal-https-with-lets-encrypt-linode-dns-and-traefik/ is a great blog post that covers how to configure Traefik 2 with Linode DNS as the DNS Challenge provider.

**Comment by displague** [comment]
Closing this. I'll keep the branch available but there's not too much in here and it is very dated considering Traefik 2 has been available for some time and I believe the installation should look very different.

**Pull request closed without merging**
