### PR TITLE
Fix small typo on example/README.md

### PR DESCRIPTION
**Pull request by altmas5**
### General:

* [x] Have you removed all sensitive information, including but not limited to access keys and passwords?
* [x] Have you checked to ensure there aren't other open or closed pull requests for the same bug/feature/question?
* [x] Have you followed our [pull request guidelines](CONTRIBUTING.md)?

### CODE REVIEW

**Review by 0xch4z — APPROVED** [review]

**Comment by 0xch4z** [comment]
As always, thank you!!

**Comment by phillc** [comment]
I wonder how we keep making the
the copy errors like this.

**Comment by altmas5** [comment]
That's a really common typo on English language

**Comment by altmas5** [comment]
> As always, thank you!!

You're welcome!

**Pull request merged**
